language: objective-c
os: osx
sudo: required
dist: trusty
node_js:
- '7.5'
before_install:
- chmod +x scripts/travis/package-and-upload.sh
- npm install -g npm@2.14.5
- npm install -g cordova ionic
script:
- npm install
- npm test
- chmod +x hooks/after_prepare/010_add_platform_class.js
- cordova platform add android
- cordova platform add ios
- ionic build android
- ionic build ios --release
- ionic build ios --release
after_success:
- ./scripts/package-and-upload.sh
env:  
  global:
  - APP_NAME="PepSII"
  - DEVELOPER_NAME="iPhone Distribution: Company LLC (IOSAPPID)"
  - PROFILE_NAME="PROFILE_NAME"
  - PROFILE_UUID="11111-11111-1111111-111111-11111"
  - DELIVER_WHAT_TO_TEST="Initial Front"
  - HOCKEYAPP_UPLOAD_BRANCH="master"